### ISSUE TITLE
reportError throws assertion: setState() called after dispose()

### ISSUE THREAD

**Issue by kw2019ltd** [Baseflow/octo_image#1]
getting below in logs with below example:
```
    return OctoImage(
      image: CachedNetworkImageProvider(url),
      placeholderBuilder: (context) =>
          context.watch<ThemeProvider>().isLightTheme
              ? CircularProgressIndicator(
                  backgroundColor: Theme.of(context).primaryColor,
                  valueColor: const AlwaysStoppedAnimation(Colors.white),
                )
              : CircularProgressIndicator(
                  backgroundColor: Theme.of(context).primaryColor,
                ),
      errorBuilder: (context, url, dynamic error) => _sizedContainer(
        Icon(
          Icons.error,
          color: Colors.red,
        ),
      ),
    );
```

```
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following assertion was thrown when reporting an error to an image listener:
setState() called after dispose(): _ImageState#8fa88(lifecycle state: defunct, not mounted, stream: ImageStream#ebcf8(MultiFrameImageStreamCompleter#209a4, [960×720] @ 1.0x, 1 listener), pixels: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
#2      _ImageState._getListener.<anonymous closure> (package:flutter/src/widgets/image.dart:1116:13)
#3      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:504:24)
#4      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:439:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════════════════════════
setState() called after dispose(): _ImageState#b0bda(lifecycle state: defunct, not mounted, stream: ImageStream#6f11d(MultiFrameImageStreamCompleter#366d4, [1632×1224] @ 1.0x, 1 listener), pixels: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by lunedam-git** [comment]
Getting the same error as @kw2019ltd 

Flutter Channel beta, v1.17.0, on Mac OS X 10.15.4
cached_network_image: ^2.0.0

**Comment by renefloor** [comment]
I'd guess it is related to this issue: https://github.com/flutter/flutter/issues/56454
Does it crash fill your console?

**Comment by kw2019ltd** [comment]
looks the same issue to me.

**Comment by lunedam-git** [comment]
Certainly related to when items are scrolled beyond the viewport, yes. Using only CachedNetworkImage is fine but as soon as octo_image is added to the mix this problem kicks off.

**Comment by kw2019ltd** [comment]
Yes it was working fine before using the plugin now facing this error.

**Comment by renefloor** [comment]
Just made a PR on the Flutter repo, but that will at least take some time before it hits the stable branch.

**Comment by renefloor** [comment]
PR on the Flutter repo was merged into master today, so this issue should be resolved now. Will take some time before it is available to you though (if you're not using the master channel).
